apiVersion: v1
kind: Service
metadata:
  name: contoso-air-service
spec:
  sessionAffinity: ClientIP
  ports:
    - name: "8080"
      port: 8082
      targetPort: 8080
  selector:
    app: contoso-air
  type: NodePort