apiVersion: apps/v1
kind: Deployment
metadata:
#  name: batch-visualizer-auth-deployment
  name: ContosoAir_APP
spec:
  replicas: 5
  selector:
    matchLabels:
      app: batch-visualizer-auth
  template:
    metadata:
      labels:
        app: batch-visualizer-auth
    spec:
      containers:
        - name: batch-visualizer-auth
          image: och5351/kubernetes_test:test_app
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'
      #imagePullSecrets:
      #  - name: my-secret