apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-air-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: contoso-air
  template:
    metadata:
      labels:
        app: contoso-air
    spec:
      containers:
        - name: contoso-air
          image: och5351/kubernetes_test:test_app
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'
      #imagePullSecrets:
      #  - name: my-secret