apiVersion: apps/v1
kind: Deployment
metadata:
  name: ContosoAir-deployment
  labels:
    app: ContosoAir
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ContosoAir
  template:
    metadata:
      labels:
        app: ContosoAir
    spec:
      containers:
        - name: ContosoAir
          image: och5351/kubernetes_test:test_app
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'
      #imagePullSecrets:
      #  - name: my-secret